config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  devise_for :users, :controllers => { :omniauth_callbacks => "my_engine/omniauth_callbacks" }, :class_name => "FormUser", module: :devise

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'welcome/index'

  # facebook sign in
  # devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  # google+ sign in
  # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :custome_bookings
  resources :bookings

  resources :customers
  resources :cleaners

  root 'bookings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Routing for facebook authentication controller
  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end
end

app/models/cleaner.rb
class Cleaner < ApplicationRecord
  has_many :bookings

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates_inclusion_of :quality_score, in: 0.0..5.0, message: 'This site is only for 0.0 ~ 5.0'

  def name
    return first_name + " " + last_name
  end
end

app/controllers/cleaners_controller.rb
class CleanersController < ApplicationController
  before_action :set_cleaner, only: [:show, :edit, :update, :destroy]

  # GET /cleaners
  # GET /cleaners.json
  def index
    @cleaners = Cleaner.all
  end

  # GET /cleaners/1
  # GET /cleaners/1.json
  def show
  end

  # GET /cleaners/new
  def new
    @cleaner = Cleaner.new
  end

  # GET /cleaners/1/edit
  def edit
  end

  # POST /cleaners
  # POST /cleaners.json
  def create
    @cleaner = Cleaner.new(cleaner_params)

    respond_to do |format|
      if @cleaner.save
        format.html { redirect_to @cleaner, notice: 'Cleaner was successfully created.' }
        format.json { render :show, status: :created, location: @cleaner }
      else
        format.html { render :new }
        format.json { render json: @cleaner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cleaners/1
  # PATCH/PUT /cleaners/1.json
  def update
    respond_to do |format|
      if @cleaner.update(cleaner_params)
        format.html { redirect_to @cleaner, notice: 'Cleaner was successfully updated.' }
        format.json { render :show, status: :ok, location: @cleaner }
      else
        format.html { render :edit }
        format.json { render json: @cleaner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cleaners/1
  # DELETE /cleaners/1.json
  def destroy
    @cleaner.destroy
    respond_to do |format|
      format.html { redirect_to cleaners_url, notice: 'Cleaner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cleaner
      @cleaner = Cleaner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cleaner_params
      params.require(:cleaner).permit(:first_name, :last_name, :email, :quality_score)
    end
end

app/helpers/cleaners_helper.rb
module CleanersHelper
end

app/views/cleaners/_form.html.erb
<%= form_for(cleaner, html: {:class => "form-horizontal"}) do |f| %>
  <% if cleaner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cleaner.errors.count, "error") %> prohibited this cleaner from being saved:</h2>

      <ul>
      <% cleaner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name, class: "col-md-2 control-label" %>
    <div class="col-md-8">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :last_name, class: "col-md-2 control-label" %>
    <div class="col-md-8">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, class: "col-md-2 control-label" %>
    <div class="col-md-8">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :quality_score, class: "col-md-2 control-label" %>
    <div class="col-md-8">
      <%= f.text_field :quality_score, class: "form-control" %>
    </div>
  </div>

  <div class="actions" align="center">
    <%= f.submit class: "btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/cleaners/edit.html.erb
<h1>Editing Cleaner</h1>

<%= render 'form', cleaner: @cleaner %>

<nav aria-label="...">
  <ul class="pager">
    <li class="previous"><%= link_to 'Back', cleaners_path %></li>
    <li class="previous"><%= link_to 'Show', @cleaner %></li>
  </ul>
</nav>

app/views/cleaners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cleaners</h1>

<table class="table table-classes table-condensed">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Quality score</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% unless @cleaners.empty? %>
      <% @cleaners.each do |cleaner| %>
        <tr>
          <td><%= cleaner.first_name %></td>
          <td><%= cleaner.last_name %></td>
          <td><%= cleaner.email %></td>
          <td><%= cleaner.quality_score %></td>
          <td>
            <%= link_to 'Show', cleaner, class: 'btn btn-primary btn-sm' %>
            <%= link_to 'Edit', edit_cleaner_path(cleaner), class: 'btn btn-info btn-sm' %>
            <%= link_to 'Destroy', cleaner, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<div class="contextual">
  <%= link_to(new_cleaner_path, class: "btn btn-success") do %>
    New Cleaner <i class="icon-plus icon-white"></i>
  <% end %>
</div>

app/views/cleaners/new.html.erb
<h1>New Cleaner</h1>

<%= render 'form', cleaner: @cleaner %>

<nav aria-label="...">
  <ul class="pager">
    <li class="previous">
      <%= link_to 'Back', cleaners_path %>
    </li>
  </ul>
</nav>

app/views/cleaners/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p>
      <div class="form-group">
        <label class="col-md-2 control-label">
          First name:
        </label>
        <%= @cleaner.first_name %>
      </div>

      <div class="form-group">
        <label class="col-md-2 control-label">
          Last name:
        </label>
        <%= @cleaner.last_name %>
      </div>

      <div class="form-group">
        <label class="col-md-2 control-label">
          Email:
        </label>
        <%= @cleaner.email %>
      </div>

      <div class="form-group">
        <label class="col-md-2 control-label">
          Quality score:
        </label>
        <%= @cleaner.quality_score %>
      </div>
    </p>
  </div>

  <div class="panel-footer">
    <nav aria-label="...">
      <ul class="pager">
        <li class="previous"><%= link_to 'Back', cleaners_path %></li>
        <li class="previous"><%= link_to 'Edit', edit_cleaner_path(@cleaner) %></li>
      </ul>
    </nav>
  </div>
  
</div>