config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  devise_for :users, :controllers => { :omniauth_callbacks => "my_engine/omniauth_callbacks" }, :class_name => "FormUser", module: :devise

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'welcome/index'

  # facebook sign in
  # devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  # google+ sign in
  # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :custome_bookings
  resources :bookings

  resources :customers
  resources :cleaners

  root 'bookings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Routing for facebook authentication controller
  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end
end

app/models/custome_booking.rb
class CustomeBooking < ApplicationRecord
  belongs_to :customer
  validates :name, presence: true
  validates :customer, presence: true
end

app/controllers/custome_bookings_controller.rb
class CustomeBookingsController < ApplicationController
  before_action :set_custome_booking, only: [:show, :edit, :update, :destroy]

  # GET /custome_bookings
  # GET /custome_bookings.json
  def index
    @custome_bookings = CustomeBooking.order(created_at: :desc).includes(:customer)
  end

  # GET /custome_bookings/1
  # GET /custome_bookings/1.json
  def show
  end

  # GET /custome_bookings/new
  def new
    @custome_booking = CustomeBooking.new
    set_customers
  end

  # GET /custome_bookings/1/edit
  def edit
    set_customers
  end

  # POST /custome_bookings
  # POST /custome_bookings.json
  def create
    @custome_booking = CustomeBooking.new(custome_booking_params)
    set_customers

    respond_to do |format|
      if @custome_booking.save
        format.html { redirect_to @custome_booking, notice: 'Custome booking was successfully created.' }
        format.json { render :show, status: :created, location: @custome_booking }
      else
        format.html { render :new }
        format.json { render json: @custome_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custome_bookings/1
  # PATCH/PUT /custome_bookings/1.json
  def update
    set_customers
    respond_to do |format|
      if @custome_booking.update(custome_booking_params)
        format.html { redirect_to @custome_booking, notice: 'Custome booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @custome_booking }
      else
        format.html { render :edit }
        format.json { render json: @custome_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /custome_bookings/1
  # DELETE /custome_bookings/1.json
  def destroy
    @custome_booking.destroy
    respond_to do |format|
      format.html { redirect_to custome_bookings_url, notice: 'Custome booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custome_booking
      @custome_booking = CustomeBooking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custome_booking_params
      params.require(:custome_booking).permit(:name, :customer_id)
    end

    # Use callback to share common setup or constraints betwwen actions.
    def set_customers
      @customers = Customer.all.
         collect do |c|
            [c.name, c.id]
         end
    end
end

app/helpers/custome_bookings_helper.rb
module CustomeBookingsHelper
end

app/views/custome_bookings/_form.html.erb
<%= form_for(custome_booking, html: {:class => "form-horizontal"}) do |f| %>

    <% if custome_booking.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(custome_booking.errors.count, "error") %> prohibited this custome_booking from being saved:</h2>

        <ul>
        <% custome_booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, "Name:", class: "col-md-2 control-label" %>
      <div class="col-md-8">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-2 control-label">
        Customer Name:
      </label>
      <div class="col-md-8">
        <%= f.select :customer_id, @customers, {:include_blank => "select a customer"}, {:class => "form-control btn-danger"} %>
      </div>
    </div>

    <div class="actions" align="center">
      <%= f.submit class: "btn btn-primary btn-sm" %>
    </div>

<% end %>

app/views/custome_bookings/edit.html.erb
<h1>Editing Custome Booking</h1>

<%= render 'form', custome_booking: @custome_booking %>

<nav aria-label="...">
  <ul class="pager">
    <li class="previous"><%= link_to 'Back', custome_bookings_path %></li>
    <li class="previous"><%= link_to 'Show', @custome_booking %></li>
  </ul>
</nav>

app/views/custome_bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Custome Bookings</h1>

<table class="table table-classes table-condensed table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% unless @custome_bookings.empty? %>
      <% @custome_bookings.each do |custome_booking| %>
        <tr>
          <td><%= custome_booking.name %></td>
          <td><%= custome_booking.customer.name %></td>
          <td>
            <%= link_to 'Show', custome_booking, class: 'btn btn-default btn-xs' %>
            <%= link_to 'Edit', edit_custome_booking_path(custome_booking), class: "btn btn-info btn-xs" %>
            <%= link_to 'Destroy', custome_booking, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<div class="contextual">
  <%= link_to(new_custome_booking_path, class: "btn btn-success") do %>
    New Custome Booking <i class="icon-plus icon-white"></i>
  <% end %>
</div>

app/views/custome_bookings/new.html.erb
<h1>New Custome Booking</h1>

<%= render 'form', custome_booking: @custome_booking %>

<nav aria-label="...">
  <ul class="pager">
    <li class="previous">
      <%= link_to 'Back', custome_bookings_path %>
    </li>
  </ul>
</nav>

app/views/custome_bookings/show.html.erb
<div class="panel panel-default">

  <div class="panel-body">
    <p>
      
      <div class="form-group">
        <label class="col-md-2 control-label">
          Name:
        </label>
        <%= @custome_booking.name %>
      </div>

      <div class="form-group">
        <label class="col-md-2 control-label">
          Customer name:
        </label>
        <%= @custome_booking.customer.name %>
      </div>

    </p>
  </div>

  <div class="panel-footer">
    <nav aria-label="...">
      <ul class="pager">
        <li class="previous"><%= link_to 'Back', custome_bookings_path %></li>
        <li class="previous"><%= link_to 'Edit', edit_custome_booking_path(@custome_booking) %></li>
      </ul>
    </nav>
  </div>

</div>