config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  devise_for :users, :controllers => { :omniauth_callbacks => "my_engine/omniauth_callbacks" }, :class_name => "FormUser", module: :devise

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'welcome/index'

  # facebook sign in
  # devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  # google+ sign in
  # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :custome_bookings
  resources :bookings

  resources :customers
  resources :cleaners

  root 'bookings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Routing for facebook authentication controller
  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>
    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container-fluid">

        <div class="navbar-header">

          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to(image_tag('/assets/logo-5991c0d62a63fc4444869e6d8ef2e2bed8fb0b2d4b98311696813c4dcc33ee46.jpg', id:"logosT", size:"20x20"), bookings_path, class: 'navbar-brand' ) %>

        </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <% if user_signed_in? %>

              <ul class="nav navbar-nav">
                <li><%= link_to 'Bookings', bookings_path %></li>
                <li><%= link_to 'Custome_bookings', custome_bookings_path %></li>
                <li><%= link_to 'Customers', customers_path %></li>
                <li><%= link_to 'Cleaners', cleaners_path %></li>
              </ul>

              <form class="navbar-form navbar-left">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">search</button>
              </form>

              <!-- <p class="nav navbar-nav navbar-right">
              Logged in as <strong><%= current_user.email %></strong>. -->
              <ul class="nav navbar-nav navbar-right">
                <li class="active">
                  <%= link_to "Signout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                </li>
              </ul>

              <ul class="nav navbar-nav navbar-right">
                <li class="active">
                  <%= link_to "Upgrade Access", user_omniauth_upgrade_path( :google_oauth2 ) %>
                </li>
              </ul>

              <ul class="nav navbar-nav navbar-right">
                <li class="active">
                  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
                </li>
              </ul>

            <% else %>

              <ul class="nav navbar-nav navbar-right">
                <li class="active">  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %></li>
              </ul>

              <ul class="nav navbar-nav navbar-right">
                <li class="active">  <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></li>
              </ul>

            <% end %>
          </div>
      </div>
    </nav>

    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>

</html>